# Generated by Django 5.1.3 on 2024-11-11 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('button_1', 'Botón 1'), ('button_2', 'Botón 2')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='button_clicks',
        ),
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.button')),
                ('user_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.useractivity')),
            ],
        ),
        migrations.AddField(
            model_name='useractivity',
            name='buttons_clicked',
            field=models.ManyToManyField(through='core.ButtonClick', to='core.button'),
        ),
    ]
