# Generated by Django 5.1.3 on 2024-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_buttonclick_user_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='buttons_clicked',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='button_1_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='button_2_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
